language: erlang
script: "make && make test"
install:
  - sudo apt-get install python-tk
  - sudo pip install dash==0.36.0  # The core dash backend
  - sudo pip install dash-html-components==0.13.5  # HTML components
  - sudo pip install dash-core-components==0.43.0  # Supercharged components
  - sudo pip install dash-table==3.1.11  # Interactive DataTable component (new!)
  - sudo pip install dash-daq==0.1.0
  - sudo pip install gunicorn
  - sudo pip install codecov
after_success: "codecov"
otp_release:
- 20.0
- 19.3
- 19.2
- 19.1
- 19.0
- 18.3
- 18.2.1
- 18.2
- 18.1
- 18.0
